global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ваше Spring Boot приложение
  - job_name: 'individuals-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['individuals-api:8081']
    scrape_interval: 5s

  # Keycloak метрики
  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:9000']
    scrape_interval: 30s

  # Loki метрики
  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 15s

  # Grafana метрики
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s