openapi: 3.0.0
info:
  title: Person API
  description: REST API регистрации, получения информации о пользователях в БД
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1

paths:
  /countries:
    get:
      summary: Получение справочника стран
      responses:
        '200':
          description: Успешное получение справочника

  /person/registration:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: string
                description: userId
                example: a1b2c3d4-e5f6-7890-1234-567890abcdef


components:
  schemas:
    UserRegistrationRequest:
      type: object
      required: [firstName, lastName, email, secretKey, passportNumber,
                 phoneNumber, countryId, city, state, zipCode, address]
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 20
        lastName:
          type: string
          minLength: 2
          maxLength: 20
        email:
          type: string
          format: email
        secretKey:
          type: string
          minLength: 3
          maxLength: 20
        passportNumber:
          type: string
          minLength: 3
          maxLength: 10
        phoneNumber:
          type: string
          minLength: 10
          maxLength: 15
        countryId:
          type: integer
          minimum: 1
        city:
          type: string
          minLength: 2
          maxLength: 20
        state:
          type: string
          minLength: 2
          maxLength: 20
        zipCode:
          type: string
          minLength: 2
          maxLength: 20
        address:
          type: string
          minLength: 2
          maxLength: 128


