spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm_name}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm_name: ${KEYCLOAK_REALM:individuals}
  client_id: ${KEYCLOAK_CLIENT_ID:individuals-api}
  client_secret: ${KEYCLOAK_CLIENT_SECRET:ZmkJaSPWHNeGNnpHoCJ5lF0x1nZ4OAAy}
  admin_username: ${KEYCLOAK_ADMIN_USERNAME:geo}
  admin_password: ${KEYCLOAK_ADMIN_PASSWORD:geo}


server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/individuals-api.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true