spring:
  application:
    name: person-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      envers:
        audit_table_suffix: _audit
        revision_field_name: revision_id
        revision_type_field_name: revision_type
        store_data_at_delete: true
      hibernate:
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true
        default_schema: public
        id:
          new_generator_mappings: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    root: INFO
    org.example.personservice: DEBUG

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always